site_name: Drayage Quoter
docs_dir: docs
nav:
    - Home: sign-up.md
theme:
  name: material
  features:
    - navigation.footer
  palette:
        # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Open Sans
  logo: assets/logo.png
  favicon: assets/logo.png
extra:
  homepage: https://www.drayagequoter.com/